# fly.toml - Configuración corregida para Fly.io

app = "molecular-viewer-app"  # ✅ NOMBRE VÁLIDO
primary_region = "ord"        # Chicago (buena elección)

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  PYTHONUNBUFFERED = "1"
  CAMERA_ENABLED = "false"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
